# TODO:
# - Schema. See https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: participants.kubernetes.mojaloop.io
spec:
  group: kubernetes.mojaloop.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: participants
    singular: participant
    kind: Participant
